# Generated by Django 4.2.2 on 2023-07-17 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_authormodel_bookmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Title'),
        ),
    ]
