# Generated by Django 4.2.3 on 2023-07-13 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_authormodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('isbn10', models.IntegerField(primary_key=True, serialize=False, verbose_name='Isbn 10')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('language', models.CharField(max_length=50, verbose_name='Language')),
                ('pages', models.IntegerField(verbose_name='Pages')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.authormodel')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.publishermodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
